'use strict';

export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const UPDATE_DECK_BUILDER_INPUT = 'UPDATE_DECK_BUILDER_INPUT';
export const UPDATE_DECK_BUILDER_ARRAY = 'UPDATE_DECK_BUILDER_ARRAY';
export const UPDATE_LOGIN_FIELD = 'UPDATE_LOGIN_FIELD';
export const CHANGE_REGISTRATION_FIELD = 'CHANGE_REGISTRATION_FIELD';
export const VALIDATE_REGISTRATION_FIELD = 'VALIDATE_REGISTRATION_FIELD';
export const UPDATE_LIVE_BETS = 'UPDATE_LIVE_BETS';
export const UPDATE_STORE = 'UPDATE_STORE';
export const CLEAR_STORE = 'CLEAR_STORE';
export const CHANGE_EVENT_FIELD = 'CHANGE_EVENT_FIELD';
export const CHANGE_OPTIONAL_EVENT_FIELD = 'CHANGE_OPTIONAL_EVENT_FIELD';
export const VALIDATE_EVENT_FIELD = 'VALIDATE_EVENT_FIELD';
export const CLEAR_EVENT_CREATE = 'CLEAR_EVENT_CREATE';
