'use strict';

export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const GO_BACK = 'GO_BACK';
export const CHANGE_REGISTRATION_FIELD = 'CHANGE_REGISTRATION_FIELD';
export const UPDATE_STORE = 'UPDATE_STORE';
export const CLEAR_STORE = 'CLEAR_STORE';
export const ADD_EVENT = 'ADD_EVENT';
export const CHANGE_EVENT_FIELD = 'CHANGE_EVENT_FIELD';
export const CHANGE_LOGIN_FIELD = 'CHANGE_LOGIN_FIELD';
export const VALIDATE_REGISTRATION_FIELD = 'VALIDATE_REGISTRATION_FIELD';
export const UPDATE_EVENTS = 'UPDATE_EVENTS';
